In [2]:
import pandas as pd
import googlemaps

df = pd.read_csv("villes_france.csv", sep=',', header=None, usecols=[2,14])
df.columns = ['Nom', 'Taille']
df.sort_values('Taille', ascending=False, inplace=True)
df3 = list(df.iloc[:10]['Nom'])
print (df3)

['paris', 'marseille', 'lyon', 'toulouse', 'nice', 'nantes', 'strasbourg', 'montpellier', 'bordeaux', 'lille']

In [5]:
import googlemaps
from datetime import datetime
import json
import pandas as pd
import numpy as np

gmaps = googlemaps.Client(key='AIzaSyD1KKuGERXDjjpR212prEaYCyL8zSUdXTM')

origins = df3#["Paris","Marseille"]
destinations = origins #["Paris","Lyon"] 

distances = gmaps.distance_matrix(origins, destinations)
# print (distances)

all_adresses=list(set(distances['destination_addresses']+distances['origin_addresses']))
dico={value:key for key,value in enumerate(all_adresses)}
dico_inverse={key:value for key,value in enumerate(all_adresses)}
n=len(all_adresses)
#matrice=np.zeros(shape=(n,n))
matrice=np.full((n, n), -1)
np.fill_diagonal(matrice, 0)

x=distances
# df = pd.read_json (distances['rows'].json)
for isrc, src in enumerate(x['origin_addresses']):
    for idst, dst in enumerate(x['destination_addresses']):
        row = x['rows'][isrc]
        cell = row['elements'][idst]
        ind_origin=dico[src]
        ind_dest=dico[dst]
        if cell['status'] == 'OK':
           # print('{} to {}: {}'.format(src.split(",")[0], dst.split(',')[0], cell['distance']['text']))
            matrice[ind_origin,ind_dest]=int(cell['distance']['value']/1000)
            matrice[ind_dest,ind_origin]=int(cell['distance']['value']/1000)
        else:
            print('{} to {}: status = {}'.format(src, dst, cell['status']))

#print(dico)

resultat=pd.DataFrame(matrice,columns=[dico_inverse[i] for i in range(len(dico_inverse))])
resultat.reset_index(inplace=True)

resultat['origin']=resultat['index'].map(dico_inverse)
resultat.set_index('origin',inplace=True)
del resultat['index']
resultat

,"Lyon, France","Lille, France","Montpellier, France","Nice, France","Strasbourg, France","Bordeaux, France","Nantes, France","Marseille, France","Paris, France","Toulouse, France"
origin,,,,,,,,,,
"Lyon, France",0,690,303,470,488,553,682,314,466,537
"Lille, France",690,0,963,1159,525,800,600,1002,225,894
"Montpellier, France",303,963,0,325,787,484,824,168,747,242
"Nice, France",470,1159,325,0,784,802,1143,204,932,560
"Strasbourg, France",488,525,787,784,0,968,865,799,490,970
"Bordeaux, France",553,800,484,802,968,0,353,645,590,245
"Nantes, France",682,600,824,1143,865,353,0,986,384,586
"Marseille, France",314,1002,168,204,799,645,986,0,774,403
"Paris, France",466,225,747,932,490,590,384,774,0,678
"Toulouse, France",537,894,242,560,970,245,586,403,678,0